### ISSUE TITLE
needed lock & unlock pc

### ISSUE THREAD

**Issue by pickeld** [KjetilSv/Win10As#1]
do you think its possible to add the ability to lock (easy) & unlock (maybe possible) the pc?

**Comment by KjetilSv** [comment]
lock is easy yes.. a couple of days and i will upload a new build.
unlock .. i will try :)

**Comment by FatBasta** [comment]
You can use a command line and a custom topic, I added a 
topic: "lockcomputer"
cmdtxt: "rundll32.exe"
cmdparameters: "user32.dll, LockWorkStation"

Home-assistant sends the topic YOUR_TOPIC_HERE/lockcomputer and locks my computer when I leave home. 

Works like a charm.

**Comment by pickeld** [comment]
good job!! the hardest part is yet to come . unlocking the PC remotely  💯

**Comment by KjetilSv** [comment]
Thanks you guys, its so very rewarding that people use the stuff i make.
I'll working on a new version but things are stressfull atm,

**Comment by KjetilSv** [comment]
Lock is now implemented in the latest installer.
There is ways to do the unlock but only shady/unsafe solutions so it will not be implemented.
