### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by cmsimike** [KjetilSv/Win10As#2]
Hi,

First - thanks for all your work on this. Because of this idea, I am not able to migrate away from all the hacks I had to do to get my windows computers onto Home assistant!!

Do you plan on releasing the source code?

**Comment by KjetilSv** [comment]
Thanks :)
I probably will soon ;)

**Comment by cmsimike** [comment]
Thank you - looking forward to it!

**Comment by cmsimike** [comment]
Thank you for including the source!

**Comment by KjetilSv** [comment]
@cmsimike np, big changes comming soon™ :)
