### ISSUE TITLE
request use value from playload as command line parameters

### ISSUE THREAD

**Issue by shadow05139** [KjetilSv/Win10As#20]
i Love this project but really would love to use payload values as cmdparameters if anyone knows a way i can do this please flick me a message

**Comment by KjetilSv** [comment]
I've started write the code. It will be in json as i would like more options down the line.

**Comment by shadow05139** [comment]
Ok cool if you want I can test this feature once the codes done?

On 6/06/2019 8:58 AM, KjetilSv <notifications@github.com> wrote:

I've started write the code. It will be in json as i would like more options down the line.

**Comment by KjetilSv** [comment]
The code is now implemented. 

Exsamples:

Topic = kjetildesktop/cmd
Message = {"CommandString": "notepad","WindowStyle": "3","ExecParameters": "","MonitorId": "1"}

Topic = kjetildesktop/cmd
Message = {"CommandString": "Chome","WindowStyle": "3","ExecParameters": "http://youtube.com","MonitorId": "1"}

**Comment by shadow05139** [comment]
Cool how do I compile the new version? Cant wait play with this new feature :-)

On 8/06/2019 10:46 PM, KjetilSv <notifications@github.com> wrote:

The code is now implemented.

Exsamples:

Topic = kjetildesktop/cmd
Message = {"CommandString": "notepad","WindowStyle": "3","ExecParameters": "","MonitorId": "1"}

Topic = kjetildesktop/cmd
Message = {"CommandString": "Chome","WindowStyle": "3","ExecParameters": "http://youtube.com","MonitorId<http://youtube.com%22,%22MonitorId>": "1"}

**Comment by shadow05139** [comment]
can you please make a new release as i am unable to compile thanks
